#!/usr/bin/env python3
"""
Refresh the GitHub project statistics shown on the home page.

Queries the GitHub REST API for WebODM/WebODM and writes data/github_stats.json,
which templates/index.html reads at build time through Zola's load_data.

The file is committed, and a failed refresh leaves the previous values in place
rather than blanking the panel: a rate limit or a GitHub outage should not turn
the home page's numbers into zeroes, and should never fail the deploy. That is
also why this exits 0 on every error path.

Set GITHUB_TOKEN to lift the unauthenticated rate limit from 60 requests per
hour to 5000. GitHub Actions provides one automatically.

Requirements: pip install requests
Output:       data/github_stats.json (committed)
"""

import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

try:
    import requests
except ImportError:
    print("Error: Install dependencies first: pip install requests")
    sys.exit(1)

ROOT_DIR = Path(__file__).parent.parent
OUT_FILE = ROOT_DIR / "data" / "github_stats.json"

REPO = "WebODM/WebODM"
API_BASE = "https://api.github.com"
TIMEOUT = 20

# Years are floored to the nearest multiple of this, so the headline reads
# "10+ years" for anything from 10.0 to 14.9.
YEAR_STEP = 5


def session() -> requests.Session:
    """An API session, authenticated when a token is available."""
    s = requests.Session()
    s.headers.update({
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
        "User-Agent": "webodm.org build",
    })
    token = os.environ.get("GITHUB_TOKEN", "").strip()
    if token:
        s.headers["Authorization"] = f"Bearer {token}"
    return s


def fetch_repo(s: requests.Session) -> dict:
    """Repository metadata. Redirects are followed: the repo has been renamed."""
    r = s.get(f"{API_BASE}/repos/{REPO}", timeout=TIMEOUT, allow_redirects=True)
    r.raise_for_status()
    return r.json()


def fetch_contributor_count(s: requests.Session) -> int:
    """
    Count contributors without downloading all of them.

    Asking for one per page makes the last page number the total, which GitHub
    reports in the Link header. The alternative is paging through every
    contributor purely to count them.

    anon=1 includes commits authored from an email address that was never
    linked to a GitHub account. Without it the count is 99 rather than 116,
    matching GitHub's /graphs/contributors page, which only lists contributors
    it can resolve to an account. The tradeoff is that anonymous entries are
    email identities rather than people, so one person committing from two
    addresses counts twice.
    """
    r = s.get(f"{API_BASE}/repos/{REPO}/contributors",
              params={"per_page": 1, "anon": 1},
              timeout=TIMEOUT, allow_redirects=True)
    r.raise_for_status()

    link = r.headers.get("Link", "")
    match = re.search(r'[?&]page=(\d+)[^>]*>;\s*rel="last"', link)
    if match:
        return int(match.group(1))
    # No Link header means a single page: either one contributor, or none.
    return len(r.json())


def years_since(iso_timestamp: str) -> int:
    """
    Whole years since a timestamp, floored to YEAR_STEP.

    10.5 years reads as 10, 16 as 15, 8 as 5 -- the panel renders this with a
    trailing "+" so the rounding is never overstated.
    """
    created = datetime.fromisoformat(iso_timestamp.replace("Z", "+00:00"))
    years = (datetime.now(timezone.utc) - created).days / 365.25
    return int(years // YEAR_STEP) * YEAR_STEP


def keep_existing(reason: str) -> None:
    """Leave the committed values untouched and succeed anyway."""
    print(f"WARNING: {reason}")
    if OUT_FILE.exists():
        print(f"Keeping the existing {OUT_FILE.relative_to(ROOT_DIR)}.")
    else:
        print("No previous stats on disk; the home page will omit the panel.")
    sys.exit(0)


def main() -> None:
    s = session()
    if "Authorization" not in s.headers:
        print("Note: GITHUB_TOKEN is not set, using the unauthenticated "
              "rate limit (60 requests/hour).")

    try:
        repo = fetch_repo(s)
        contributors = fetch_contributor_count(s)
    except requests.RequestException as e:
        keep_existing(f"could not reach the GitHub API: {e}")
        return

    stars = repo.get("stargazers_count")
    created_at = repo.get("created_at")
    if not isinstance(stars, int) or not created_at or contributors <= 0:
        keep_existing("the GitHub API returned an unexpected payload")
        return

    stats = {
        "_help": (
            "Generated by scripts/build_stats.py and read by "
            "templates/index.html. Committed so a failed refresh keeps the "
            "last known numbers instead of blanking the panel."
        ),
        "repo": repo.get("full_name", REPO),
        "stars": stars,
        "contributors": contributors,
        "years": years_since(created_at),
        "created_at": created_at,
        "updated_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
    }

    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUT_FILE.write_text(json.dumps(stats, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {OUT_FILE.relative_to(ROOT_DIR)}: "
          f"{stars} stars, {contributors} contributors, "
          f"{stats['years']}+ years.")


if __name__ == "__main__":
    main()
